// SELECT UI ELEMENTS

// SET WEATHER DATA

// SET WEATHER TEMPERATURE TO A UNIT

// APP CONSTS AND VARS

// API KEY

// CHECK IF BROWSER SUPPORTS GEOLOCATION
// TRUE - USE A METHOD TO GET YOUR POSITION

// FALSE - DISPLAY A ERROR MESSAGE

// SET USER'S POSITION AND CALL API

// SHOW ERROR WHEN THERE IS AN ISSUE WITH GEOLOCATION SERVICE

// GET WEATHER FROM API PROVIDER

// DISPLAY WEATHER TO UI

// C to F conversion

// WHEN THE USER CLICKS ON THE TEMPERATURE ELEMENET

//CHECK IF IT HAS A TEMPERATURE VALUE

// TRUE - CONVERT TO F

// FALSE - KEEP IT ON C
